#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use WebsysForever\SumCommand;

$app = new Application("Welcome from Console", "v1.0.0");
$app->add(new WebsysForever\SumCommand());
$app->run();
